### ISSUE TITLE
memo_dirとは

### ISSUE THREAD

**Issue by miyamonz** [terukiokamoto/j_programinger#2]
@rijin123 
memo_dirというディレクトリがあるわけではないので、READMEではmemo フォルダ作ったと書けばよいし
そもそも中身がないならコミットをしないでよい

口うるさいおっさんみたいですみません・・・

**Comment by miyamonz** [comment]
>memo フォルダ作ったと書けばよいし

さらにいえばコミットを見ればわかるので、わざわざ言わないでも良い

**Comment by rijin123** [comment]
了解～～。

**Comment by miyamonz** [comment]
せっかくだしgithub上のコミット修正とかを練習がてらやっても良いかも、と思ったけど、ちょっと今はモチベーション低し
