### ISSUE TITLE
コミットのコメントをつける

### ISSUE THREAD

**Issue by miyamonz** [terukiokamoto/j_programinger#3]
![image](https://cloud.githubusercontent.com/assets/6331508/25551840/2a98372a-2cc6-11e7-92ba-14b434d90f6e.png)
るきさんの新しいやつを見ようかな、ってときに、コミットコメントを見て判断をするので、全部同じではなく、やった内容などを簡単にでもいいので書いてみてください

**Comment by miyamonz** [comment]
この場合は日付でも確認はできるけど

**Comment by miyamonz** [comment]
@terukiokamoto

**Comment by terukiokamoto** [comment]
おいす！
